name: 'Simple Net Experience'
description: >
  'Action for generating Neelix experiences from merged PR reviews with net '
  'weight of keyword occurrences.'
inputs:
  api-token:
    description: 'Neelix API token (should be stored as secret)'
    required: true
  consortium-id:
    description: 'ID of consortium that created experiences will belong to'
    required: true
  experience-summary:
    description: 'Message to appear above table in experience commentary'
    required: true
  keywords:
    description: >
      'Keywords and weights to use in calculating weight for Neelix experiences '
      'provided as a JSON string.'
    required: true
  activity-id:
    description: >
      'ID of an activity belonging to same consortium as experience.'
      'Sets `activity_id` field of new experience. '
  category-ids:
    description: >
      'IDs of categoris belonging to same consortium as experience. Use '
      'comma-separated list for multiple values (e.g. "1,2,3"). Adds '
      'specified categories to new experience. '
  team-ids:
    description: >
      'IDs of teams belonging to same consortium as experience. Use '
      'comma-separated list for multiple values (e.g. "1,2,3"). Adds specified '
      'teams to new experience. '
  table-header-keyword:
    description: 'Name used for "keyword" column. Default: "keyword"'
  table-header-weight:
    description: 'Name used for "weight" column. Default: "weight"'
  table-header-count:
    description: 'Name used for "count" column. Default: "count"'
  table-header-total-impact:
    description: 'Name used for "total impact" column. Default: "total impact"'
  github-token:
    description: >
      'GitHub token used to authenticate against GitHub API to retrieve PR '
      'review data.'
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Get PR review data
      id: get-reviews
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        echo "review_data<<EOF" >> "$GITHUB_ENV"
        curl -sL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github-token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" >> "$GITHUB_ENV"
        echo "EOF" >> "$GITHUB_ENV"
      shell: bash
    - uses: actions/checkout@v3
      with:
        repository: neelix-io/action-handling
        ref: pre-release
    - name: Process review data
      id: process-reviews
      uses: ./.github/actions/process-reviews
      with:
        experience-summary: ${{ inputs.experience-summary }}
        keywords: ${{ inputs.keywords }}
        review-data: ${{ env.review_data }}
        table-header-keyword: ${{ inputs.table-header-keyword }}
        table-header-weight: ${{ inputs.table-header-weight }}
        table-header-count: ${{ inputs.table-header-count }}
        table-header-total-impact: ${{ inputs.table-header-total-impact }}
    - name: Send request
      id: send-request
      uses: neelix-io/create-experience-action@dev
      with:
        api-token: ${{ inputs.api-token }}
        consortium-id: ${{ inputs.consortium-id }}
        commentary: ${{ steps.process-reviews.outputs.commentary }}
        weight: ${{ steps.process-reviews.outputs.weight }}
        activity-id: ${{ inputs.activity-id }}
        category-ids: ${{ inputs.category-ids }}
        team-ids: ${{ inputs.team-ids }}
        external-ref: "https://github.com/${{ github.repository }}/pull/${{ github.event.number }}"
