name: 'Action handling'
description: 'Action for generating Neelix experiences from merged PR reviews.'
inputs:
  # TODO: remove before project becomes public
  temp-pat:
    description: 'PAT needed temporarily while project is private'
    required: true
  api-token:
    description: 'Neelix API token (should be stored as secret)'
    required: true
  consortium-id:
    description: 'ID of consortium that created experiences will belong to'
    required: true
  keyword-1-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-1-weight:
    description: 'Weight to assign to each appearance of keyword-1'
  keyword-2-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-2-weight:
    description: 'Weight to assign to each appearance of keyword-2'
  keyword-3-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-3-weight:
    description: 'Weight to assign to each appearance of keyword-3'
  keyword-4-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-4-weight:
    description: 'Weight to assign to each appearance of keyword-4'
  keyword-5-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-5-weight:
    description: 'Weight to assign to each appearance of keyword-5'
  keyword-6-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-6-weight:
    description: 'Weight to assign to each appearance of keyword-6'
  keyword-7-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-7-weight:
    description: 'Weight to assign to each appearance of keyword-7'
  keyword-8-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-8-weight:
    description: 'Weight to assign to each appearance of keyword-8'
  keyword-9-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-9-weight:
    description: 'Weight to assign to each appearance of keyword-9'
  keyword-10-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-10-weight:
    description: 'Weight to assign to each appearance of keyword-10'
  keyword-11-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-11-weight:
    description: 'Weight to assign to each appearance of keyword-11'
  keyword-12-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-12-weight:
    description: 'Weight to assign to each appearance of keyword-12'
  keyword-13-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-13-weight:
    description: 'Weight to assign to each appearance of keyword-13'
  keyword-14-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-14-weight:
    description: 'Weight to assign to each appearance of keyword-14'
  keyword-15-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-15-weight:
    description: 'Weight to assign to each appearance of keyword-15'
  keyword-16-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-16-weight:
    description: 'Weight to assign to each appearance of keyword-16'
  keyword-17-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-17-weight:
    description: 'Weight to assign to each appearance of keyword-17'
  keyword-18-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-18-weight:
    description: 'Weight to assign to each appearance of keyword-18'
  keyword-19-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-19-weight:
    description: 'Weight to assign to each appearance of keyword-19'
  keyword-20-value:
    description: 'Keyword to use in calculating weight for Neelix experiences'
  keyword-20-weight:
    description: 'Weight to assign to each appearance of keyword-20'
runs:
  using: composite
  steps:
    - name: Consolidate keywords
      id: consolidate-keywords
      run: |
        # concatenate keywords and weights into string like v1,w1:v2,w2:
        for i in {1..20}
        do if [[ -n "${{ inputs.keyword-${i}-value }}" && -n "${{ inputs.keyword-${i}-weight }}" ]]
        then
          KEYWORDS="$KEYWORDS:${{ inputs.keyword-${i}-value }},${{ inputs.keyword-${i}-weight }}"
        fi
        done
        # remove leading colon
        if [[ -n "$KEYWORDS" ]]
        then
          KEYWORDS=${KEYWORDS:1}
        fi
        echo "$KEYWORDS"
        echo "keywords=$KEYWORDS" >> "$GITHUB_ENV"
      shell: bash
    - name: Get PR review data
      id: get-reviews
      run: |
        REPO=${{ github.repository }}
        echo "repo: $REPO"
        PR_NUMBER=${{ github.event.number }}
        echo "pr number: $PR_NUMBER"
        echo "review_data<<EOF" >> "$GITHUB_ENV"
        curl -sL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews >> "$GITHUB_ENV"
        echo "EOF" >> "$GITHUB_ENV"
      shell: bash
    - uses: actions/checkout@v3
      with:
        repository: neelix-io/action-handling
        ref: build-weight
        token: ${{ inputs.temp-pat }}  # TODO: remove before project becomes public
    - name: Process review data
      id: process-reviews
      uses: ./.github/actions/process-reviews
      with:
        review-data: ${{ env.review_data }}
        keywords: ${{ env.keywords }}
    - name: Send request
      id: send-request
      uses: neelix-io/generic-action@build-weight
      with:
        api-token: ${{ inputs.api-token }}
        consortium-id: ${{ inputs.consortium-id }}
        commentary: ${{ steps.process-reviews.outputs.commentary }}
        weight: ${{ steps.process-reviews.outputs.weight }}
