name: 'Process reviews'
description: 'Processes PR reviews and outputs data for a Neelix experience'
inputs:
  experience-summary:
    description: 'Message to appear above table in experience commentary'
    required: true
  keywords:
    description: 'User-configured keywords and associated weights'
  review-data:
    description: 'Data from PR review'
outputs:
  commentary:
    description: 'Commentary for Neelix experience'
  weight:
    description: 'Weight of Neelix experience'
runs:
  using: 'node16'
  main: 'dist/index.js'
