name: 'Get review data'
description: 'Retrieves necessary data from GitHub API'
inputs:
  github-token:
    description: 'Token used to fetch data from GitHub API'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
outputs:
  review-data:
    description: 'Simplified, combined review data'
runs:
  using: 'node16'
  main: 'dist/index.js'
